### ISSUE TITLE
Where is ares-novacom

### ISSUE THREAD

**Issue by philippe-elsass-deltatre** [webosose/ares-cli#63]
You can't connect to a TV without `ares-novacom`...

cf. https://webostv.developer.lge.com/develop/app-test/using-devmode-app/

**Comment by mariotaku** [comment]
https://www.webosbrew.org/pages/configuring-sdk.html

**Comment by ssuminahn** [comment]
https://webostv.developer.lge.com/sdk/installation/download-installer/

> You can't connect to a TV without `ares-novacom`...
> 
> cf. https://webostv.developer.lge.com/develop/app-test/using-devmode-app/

webosose/ares-cli supports webOS OSE. If you want to download CLI that supports webOS TV, download webOS TV SDK from the link below.
https://webostv.developer.lge.com/sdk/installation/download-installer/
