### ISSUE TITLE
ares-package on Windows does not have a way to set correct file mode to executable files

### ISSUE THREAD

**Issue by panreyes** [webosose/ares-cli#68]
ares-package works almost flawlessly in Windows, but because Windows does not have executable bits in NTFS, they cannot be set before packaging.

I solved it for me by forcing every packaged file to use permissions mode 0777 by changing ares-cli/lib/package.js:1146:
```
            } else if (entry.props.type === "File") {
                // Add other user's readable permission to all files
                entry.props.mode = 511; // 0777
            }
```

**Comment by ssuminahn** [comment]
@panreyes 
I'm so sorry, I guess I didn't fully understood your post before.
We knew that in the case of packaging a app through ares-package in Windows, the file permission could not be given correctly. To solve this, there is the way to solve it using `package.properties` file.

The format of `package.properties` file as below, and the file is located under an app or service directory like same path `appinfo.json` or `services.json`.

- Format of `package.properties`
:  `filemode.<Three permission triads>=<filename including extension>`

- Location of `package.properties`
app/
 +--- appinfo.json
 +--- package.properties
 +--- (...)
OR
service/
 +--- services.json
 +--- package.properties
 +--- (...)

- For example, file names are `test` and `data.json` and to set permission 755.
filemode.755=test,data.json
OR
filemode.755=test
filemode.755=data.json

I hope my answer is enough to solve your problem. And the missing guide on this will be updated later.
Thank you for your interest and we look forward to your continued interest and support in the future :)
