### ISSUE TITLE
ares-device -c capture.png failes with unknown method "captureCompositorOutput"

### ISSUE THREAD

**Issue by baclark774** [webosose/ares-cli#75]
Running the following command on 2.3.1 while attempting to generate a screenshot:

ares-device -c screen.png -d device_name

Results in following error:

[Info] Set target device : device_name
ares-device ERR! [com.webos.surfacemanager failure]: luna-send command failed <Unknown method "captureCompositorOutput" for category "/">

Appreciate any help you can provide.

**Comment by ssuminahn** [comment]
When I tested on OSE v2.15 with the CLI v2.3.1, it worked normally.
I think there is a problem with your target device. Please try again after rebooting the target device.

However if it repeats, Please let me know the result after executing the command below.
`ares-device -i -d device_name`
I would like to know your target device information.
