### ISSUE TITLE
Cannot install application

### ISSUE THREAD

**Issue by konraddysput** [webosose/ares-cli#95]
Hey,

Recently webos informed me I need to update my developer application to continue using it - and I did that. After TV restart I recognized my custom apps are not there anymore. When I try to install them once again I'm receiving:

```

PS C:\Users\konra>  ares-install valid-path-to-file -d tv
[Info] Set target device : tv
ares-install ERR! [ssh exec failure]: Command '/bin/rm -rf /media/developer/temp && /bin/mkdir -p /media/developer/temp' exited with code=1
ares-install ERR! [ssh exec failure]: (Original Message: rm: can't remove '/media/developer/temp': Permission denied)
```

Before the update I was using this command all the time.

**Comment by geoffmmorgan** [comment]
We are seeing this issue as well after the update, so far have not found a workaround

**Comment by ssuminahn** [comment]
@konraddysput, @geoffmmorgan 
We only support webOS OSE. There is a separate CLI that supports webOS TV.
You can get the CLI for your TV from the site below.
I'm sorry for the inconvenience.

https://webostv.developer.lge.com

**Comment by konraddysput** [comment]
@ssuminahn I'm not sure if I follow. I go to the page, then to the development side and I see this - https://webostv.developer.lge.com/develop/tools/cli-introduction isn't this an introduction to this CLI tool?

**Comment by ssuminahn** [comment]
@konraddysput
You must use the CLI for TV, not the CLI for OSE
Please refer to the following link.
https://webostv.developer.lge.com/develop/tools/cli-installation.

And about webOS TV, you can get help from the link below. 
https://forum.webostv.developer.lge.com/
